### ISSUE TITLE
Problems with intial setup on Docker Win 10

### ISSUE THREAD

**Issue by Niebvelungen** [Force-of-Wind/fowsim#131]
I found out when copying the project and composing it that the Docker instance would not start.
In my case in the docker-compose.yaml i had to mount the **web volume** to a specific path:
docker-compose.yaml:

```
.......
services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - C:\R\fowsim:/usr/src/app/
    expose:
      - 8000
......
```
And in the Dockerfile i had to comment out the 
`ENTRYPOINT ["/usr/src/app/entrypoint.sh"]` script 
else the web instance would not start complaining it does not have the file
  
![image](https://github.com/Force-of-Wind/fowsim/assets/74566937/fa063ea7-6518-4d42-876f-c03c0e902814)
